declare namespace Asset {
  type GMAnimCurve = any;
  type GMSound = any;
  type GMObject = any;
  type GMSprite = any;
  type GMFont = any;
  type GMParticleSystem = any;
  type GMAudioGroup = any;
  type GMPath = any;
  type GMRoom = any;
  type GMShader = any;
  type GMScript = any;
  type GMSequence = any;
  type GMTileSet = any;
  type GMTimeline = any;
  type Script = any;
  type GMTexturePage = any;
  type Asset = any;
}
