declare interface GmInstance {
  font_texture_page_size: Real;
  readonly instance_count: Real;
  readonly instance_id: Array<Id.Instance>;
  alarm: Array<Real>;
  depth: Real;
  direction: Real;
  friction: Real;
  gravity: Real;
  gravity_direction: Real;
  hspeed: Real;
  readonly id: Id.Instance;
  layer: Id.Layer;
  persistent: Bool;
  solid: Bool;
  speed: Real;
  visible: Bool;
  readonly managed: Bool;
  vspeed: Real;
  x: Real;
  xprevious: Real;
  xstart: Real;
  y: Real;
  yprevious: Real;
  ystart: Real;
  readonly object_index: Asset.GMObject;
  readonly event_number: Constant.EventNumber;
  readonly event_object: Asset.GMObject;
  readonly event_type: Constant.EventType;
  path_endaction: Constant.PathAction;
  readonly path_index: Asset.GMPath;
  path_orientation: Real;
  path_position: Real;
  path_positionprevious: Real;
  path_scale: Real;
  path_speed: Real;
  room: Asset.GMRoom;
  readonly room_first: Asset.GMRoom;
  room_height: Real;
  readonly room_last: Asset.GMRoom;
  room_persistent: Bool;
  room_width: Real;
  in_sequence: Bool;
  readonly sequence_instance: Struct.SequenceInstance;
  drawn_by_sequence: Bool;
  readonly bbox_bottom: Real;
  readonly bbox_left: Real;
  readonly bbox_right: Real;
  readonly bbox_top: Real;
  image_alpha: Real;
  image_angle: Real;
  image_blend: Constant.Color;
  image_index: Real;
  readonly image_number: Real;
  image_speed: Real;
  image_xscale: Real;
  image_yscale: Real;
  mask_index: Asset.GMSprite;
  readonly sprite_height: Real;
  sprite_index: Asset.GMSprite;
  readonly sprite_width: Real;
  readonly sprite_xoffset: Real;
  readonly sprite_yoffset: Real;
  timeline_index: Asset.GMTimeline;
  timeline_loop: Bool;
  timeline_position: Real;
  timeline_running: Bool;
  timeline_speed: Real;
  view_camera: Array<Id.Camera>;
  readonly view_current: Real;
  view_enabled: Bool;
  view_hport: Array<Real>;
  view_surface_id: Array<Id.Surface>;
  view_visible: Array<Bool>;
  view_wport: Array<Real>;
  view_xport: Array<Real>;
  view_yport: Array<Real>;
  readonly debug_mode: Bool;
  readonly fps: Real;
  readonly fps_real: Real;
  readonly application_surface: Id.Surface;
  readonly program_directory: String;
  readonly temp_directory: String;
  readonly working_directory: String;
  readonly event_data: Id.DsMap;
  keyboard_key: Constant.VirtualKey;
  keyboard_lastchar: String;
  keyboard_lastkey: Constant.VirtualKey;
  keyboard_string: String;
  mouse_button: Constant.MouseButton;
  mouse_lastbutton: Constant.MouseButton;
  readonly mouse_x: Real;
  readonly mouse_y: Real;
  cursor_sprite: Asset.GMSprite;
  readonly game_display_name: String;
  readonly game_id: Real;
  readonly game_project_name: String;
  readonly game_save_id: String;
  readonly current_day: Real;
  readonly current_hour: Real;
  readonly current_minute: Real;
  readonly current_month: Real;
  readonly current_second: Real;
  readonly current_time: Real;
  readonly current_weekday: Real;
  readonly current_year: Real;
  readonly delta_time: Real;
  readonly os_browser: Constant.BrowserType;
  readonly os_device: Constant.DeviceType;
  readonly os_type: Constant.OperatingSystem;
  readonly os_version: Real;
  phy_active: Bool;
  phy_angular_damping: Real;
  phy_angular_velocity: Real;
  phy_bullet: Bool;
  readonly phy_collision_points: Real;
  readonly phy_collision_x: Real;
  readonly phy_collision_y: Real;
  readonly phy_col_normal_x: Real;
  readonly phy_col_normal_y: Real;
  readonly phy_com_x: Real;
  readonly phy_com_y: Real;
  readonly phy_dynamic: Bool;
  phy_fixed_rotation: Bool;
  readonly phy_inertia: Real;
  readonly phy_kinematic: Bool;
  phy_linear_damping: Real;
  phy_linear_velocity_x: Real;
  phy_linear_velocity_y: Real;
  readonly phy_mass: Real;
  phy_position_x: Real;
  readonly phy_position_xprevious: Real;
  phy_position_y: Real;
  readonly phy_position_yprevious: Real;
  phy_rotation: Real;
  readonly phy_sleeping: Bool;
  readonly phy_speed: Real;
  phy_speed_x: Real;
  phy_speed_y: Real;
  readonly browser_height: Real;
  readonly browser_width: Real;
  readonly webgl_enabled: Bool;
  readonly argument_relative: Real;
  argument: ArgumentIdentity;
  argument0: ArgumentIdentity;
  argument1: ArgumentIdentity;
  argument2: ArgumentIdentity;
  argument3: ArgumentIdentity;
  argument4: ArgumentIdentity;
  argument5: ArgumentIdentity;
  argument6: ArgumentIdentity;
  argument7: ArgumentIdentity;
  argument8: ArgumentIdentity;
  argument9: ArgumentIdentity;
  argument10: ArgumentIdentity;
  argument11: ArgumentIdentity;
  argument12: ArgumentIdentity;
  argument13: ArgumentIdentity;
  argument14: ArgumentIdentity;
  argument15: ArgumentIdentity;
  readonly argument_count: Real;
  readonly in_collision_tree: Bool;
  room_speed: Real;
  room_caption: String;
  score: Real;
  lives: Real;
  health: Real;
  show_score: Bool;
  show_lives: Bool;
  show_health: Bool;
  caption_score: String;
  caption_lives: String;
  caption_health: String;
  readonly event_action: Real;
  readonly gamemaker_pro: Bool;
  readonly gamemaker_registered: Bool;
  error_occurred: Bool;
  error_last: Bool;
  background_colour: Constant.Color;
  background_showcolour: Real;
  background_color: Constant.Color;
  background_showcolor: Bool;
  readonly display_aa: Real;
  readonly async_load: Id.DsMap;
  readonly iap_data: Undefined;
  readonly rollback_current_frame: Real;
  readonly rollback_confirmed_frame: Real;
  readonly rollback_event_id: Real;
  readonly rollback_event_param: Asset.GMObject;
  readonly rollback_game_running: Bool;
  readonly rollback_api_server: String;
  readonly player_id: Real;
  readonly player_local: Bool;
  readonly player_avatar_url: String;
  readonly player_avatar_sprite: Asset.GMSprite;
  readonly player_type: String;
  readonly player_user_id: String;
}